package com.techrecommendation.rules

import com.stack_advisor.stack_advisor_backend.requests.ProjectRequirementsRequest

import com.stack_advisor.stack_advisor_backend.models.enums.project.ProjectType
import com.stack_advisor.stack_advisor_backend.models.enums.project.TeamSize
import com.stack_advisor.stack_advisor_backend.models.enums.project.AppType
import com.stack_advisor.stack_advisor_backend.models.enums.project.TimeToShow

import com.stack_advisor.stack_advisor_backend.models.enums.language.Purpose
import com.stack_advisor.stack_advisor_backend.models.enums.language.EntryThreshold
import com.stack_advisor.stack_advisor_backend.models.enums.language.EntryThreshold

import com.stack_advisor.stack_advisor_backend.models.enums.dataStorage.StorageLocation

import com.stack_advisor.stack_advisor_backend.drools.data.LanguageRecommended
import com.stack_advisor.stack_advisor_backend.drools.data.DataStorageRecommended
import com.stack_advisor.stack_advisor_backend.drools.data.FrameworkRecommended

rule "Fast to Show"
    when
        $request: ProjectRequirementsRequest(
            timeToShow == TimeToShow.FAST
        )
        $LanguageResult: LanguageRecommended(
            language.entryThreshold = EntryThreshold.LOW
        )
        $DataStorageResult: DataStorageRecommended(
            dataStorage.storageLocation = StorageLocation.LOCAL
        )
    then
        $LanguageResult.setScore($LanguageResult.getScore() + 9.0);
        $DataStorageResult.setScore($DataStorageResult.getScore() + 8.0);
end